
spring:
  datasource:
    driver-calss-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
#    password: root

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
